[WIP] HH-184574 : Migration to jakarta
hhru/hh-common-errors pull request #9
Opened 2023-06-30 09:43 UTC by vbazhmin

2023-07-06 09:34 UTC, nicholasgribanov approved these changes

2023-07-07 08:31 UTC, pvorlov requested changes

2023-07-07 08:31 UTC, pvorlov commented on pom.xml
> +        <dependency>
Лишнее, тянется из jakarta.ws.rs-api

2023-07-07 08:33 UTC, pvorlov commented on pom.xml
> +        <dependency>
А там вложенный provided теперь, ок

2023-07-07 08:33 UTC, pvorlov approved these changes

2023-07-13 09:08 UTC, vbazhmin commented
squashed and rebased

2023-07-13 09:08 UTC, merged